version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli@17.1.3
  pre_build:
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - ng build --prod
    finally:
      - echo final block echo

artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'
